#! /bin/sh
set -euo pipefail

echo "Configuring sudo"
apt-get update
apt-get -y install sudo
whoami
sed -i 's|^.*\(WHEEL_USERS ALL=(ALL:ALL) NOPASSWD: ALL\)$|\1|' /etc/sudoers
grep 'WHEEL_USERS' /etc/sudoers
echo "sudo configured"

